### ISSUE TITLE
connecting a MSSQL-DB is not possible

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/ipl-sql#58]
I tried to create a new module to connect a MSSQL-DB, but it is not possible. It's the same problem as directly in icingaweb2 https://github.com/Icinga/icingaweb2/issues/4937. But here it this line https://github.com/Icinga/ipl-sql/blob/cbe5d0854ef0612c7108b84b0864b4e69e81afd1/src/Adapter/Mssql.php#L19. Here is the entry 'sqlsrv' missing. 
I can create successfully an object, but After running an sql-statement or as object oriented like
```
$this->db->exec(
               #           (new Insert())
               #               ->into('<table>')
               #               ->values([...
```
I get always the error "Undefined offset: 0". 

If I use the 'classic' PDO module, everything works fine.

**Comment by lippserd** [comment]
After a second thought, I think I know where the problem comes from. `array_intersect()` preserves the keys and we always access index 0, which may exist.

**Comment by stevie-sy** [comment]
I'll test this and report back

**Comment by stevie-sy** [comment]
I'll tested it with array_values() and it works. 

But after that change I got following error:

> SQLSTATE[IMSSP]: An invalid keyword 'host' was specified in the DSN string.

Digging deeper and comparing with the possible param list which Microsoft offers (https://learn.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver15) we can see, that `host` is not a correct param. So this line is wrong https://github.com/Icinga/ipl-sql/blob/cbe5d0854ef0612c7108b84b0864b4e69e81afd1/src/Adapter/Mssql.php#L25. The correct param for this is `server`. As well `dbname `in this line https://github.com/Icinga/ipl-sql/blob/cbe5d0854ef0612c7108b84b0864b4e69e81afd1/src/Adapter/Mssql.php#L37 as also incorrect. The correct param is `database`. 

As well the if-step for the seperator doesn't work for me. Because if we check the docs from MS again, there is no diffrence between Linux and Windows. It's always a `,`

At the end is this the DSN with the "classic" PDO class:
`sqlsrv:server=<server>,<port>;Database=<databasename`

And with the patches above everything works as expected. 

The only problem which is left for me, but this is another job, is that this construction from the docs doesn't work in my code

> $connection->exec(
>     (new Insert())
>         ->into('customer')
>         ->values([
>             'id'   => 42,
>             'name' => 'John Deo'
>         ])
> );

With this I get following error although I load the correct classes:

> PDO::exec() expects parameter 1 to be string, object given

But this works:
`$connection->exec('INSERT INTO ...')`

**Comment by nilmerg** [comment]
> And with the patches above everything works as expected.

Thanks for digging so deep! :grin:

> this construction from the docs doesn't work in my code

That's outdated, I'm sorry. It should be the method `prepexec` which accepts objects.

**Comment by stevie-sy** [comment]
> Thanks for digging so deep! 😁
Was only possible because of the new knowledge we got from you 😄 . If it helps, then it is fine. 
 
 
> That's outdated, I'm sorry. It should be the method `prepexec` which accepts objects.
Then everything is clear. With this it also works as expected. So the docs needs also a patch 😎

**Comment by nilmerg** [comment]
> Because if we check the docs from MS again, there is no diffrence between Linux and Windows. It's always a `,`

Please point me to the exact location in the documentation mentioning this. I didn't find it myself, but would like to have a official statement on this. 😉

**Comment by nilmerg** [comment]
Yes, sure :sweat_smile:. Though, being this a Microsoft documentation, this implies to me that it applies to Windows without any mentioning of it. That this also applies to Linux, is nowhere mentioned.

But to be fair, the [PHP documentation](https://www.php.net/manual/en/ref.pdo-sqlsrv.connection.php) only mentions the comma as well. But then again, the [PHP documentation for dblib](https://www.php.net/manual/en/ref.pdo-dblib.connection.php) doesn't mention the difference as well, but there's one.

So, I guess the only option to be sure now is to really try it out. Have you tried it on both kinds of operating systems? You don't have to try it on Windows to check if the comma is correct (I suppose the Microsoft documentation on this is correct) but please do so on Linux, if you haven't already.

You could already try out #59 while you're at it. :grin:

**Comment by stevie-sy** [comment]
ok, i love it when docs contradict each other 😂  .

Here is another doc from Microsoft which I linked also in the icingaweb2-issue;: https://learn.microsoft.com/de-de/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15 here are also examples, where they used only the `,`.

> So, I guess the only option to be sure now is to really try it out. 

And as written above for only the `,` was working for me, not the `;` Or should I test more?

But what you mean with

> Have you tried it on both kinds of operating systems?

Testing the code also on a Windows Server? If yes, I can only test this on our Linux Servers. 

> You could already try out https://github.com/Icinga/ipl-sql/pull/59 while you're at it.

Fine, I test it after the OSMC 😉

**Comment by stevie-sy** [comment]
The last days I tested this modified class and it works fine for me with the driver package "msodbcsql117", big thank you 🎉 . Because I saw you included the Parameter "TrustServerCertificate" for the driver package "msodbcsql118" I tested this also. Also this works fine! 🚀.

**Comment by nilmerg** [comment]
You're welcome. And thanks for the test! :+1:
