### ISSUE TITLE
Support for SSL connection to MySQL

### ISSUE THREAD

**Issue by MrStrix** [Icinga/ipl-sql#9]
The constructor of the PDO object in https://github.com/Icinga/ipl-sql/blob/3932b3e8082c32246d66ae3653666c2381b43484/src/Connection.php#L146 does not correctly take options into account. We temporarily established an SSL connection by doing the following:

```
    protected function createPdoAdapter()
    {
        $adapter = $this->getAdapter();

        $config = $this->getConfig();

	$fullconf = $adapter->getOptions($config);
	$fullconf[PDO::MYSQL_ATTR_SSL_CA] = "/etc/ssl/certs/ca-bundle.crt";

        return new PDO(
            $adapter->getDsn($config),
            $config->username,
            $config->password,
            $fullconf 
        );
    }
```

`$adapter->getOptions` does not format a correct options array as specified in http://php.net/manual/en/ref.pdo-mysql.php

**Comment by nilmerg** [comment]
Nope, as mentioned over at x509, that's to be fixed/supported here.

**Comment by relgames** [comment]
Hi, do you have any updates? I see a PR but the ticket is still open...
